### ISSUE TITLE
Disabled Extensions

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#1]
There are many possible ideas floating around the `@Disabled` annotation:

* [X] disable tests by evaluating a script (e.g., JavaScript, Groovy, etc)
  - See `@EnabledIf` and `@DisabledIf` in Jupiter 5.1
* [X] disable tests on selected OS (#2, junit-team/junit5#219, [proof of concept](https://github.com/CodeFX-org/demo-junit-5/blob/master/src/main/java/org/codefx/demo/junit5/OsCondition.java))
  - See `@EnabledOnOs` and `@DisabledOnOs` in Jupiter 5.1
* [X] disable tests on selected Java versions
  - See `@EnabledOnJre` and `@DisabledOnJre` in Jupiter 5.1
* [X] system property matches a pattern ([comment in #219](https://github.com/junit-team/junit5/issues/219#issuecomment-226761964))
  - See `@EnabledIfSystemProperty` and `@DisabledIfSystemProperty` in Jupiter 5.1
* [X] environment variable matches a pattern ([comment in #219](https://github.com/junit-team/junit5/issues/219#issuecomment-226761964))
  - See `@EnabledIfEnvironmentVariable` and `@DisabledIfEnvironmentVariable` in Jupiter 5.1
* [X] disable all tests in a class except for one (junit-team/junit5#346, [proof of concept](https://github.com/selesy/junit5-extensions))
  - not yet implemented, but tracked by #71
* [X] current date/time matches some criteria, e.g. `@DisabledUntil` ([comment in #219](https://github.com/junit-team/junit5/issues/219#issuecomment-226761964)) ~> #366 
  - See also: [@EnabledOnDayOfWeek](https://github.com/sbrannen/junit5-demo/blob/master/src/main/java/org/junit/jupiter/api/condition/EnabledOnDayOfWeek.java) and [@DisabledOnDayOfWeek](https://github.com/sbrannen/junit5-demo/blob/master/src/main/java/org/junit/jupiter/api/condition/DisabledOnDayOfWeek.java) ~> it's a fun idea, but unlikely to be actually useful
* [X] until a Github/Gitlab (extensible) issue has been closed ~> #367

It is conceivable to create a universal `@DisabledIf` annotation that covers all of these cases but instead of going there from the outset, it might make more sense to tackle individual use cases first and look for room for generalization later.

**Comment by sbrannen** [comment]
> it might make more sense to tackle individual use cases first and look for room for generalization later.

👍 

In case you're not aware of it, Spring 5 milestones already support `@EnabledIf` and `@DisabledIf` variants that accept SpEL expressions which make the implementation of custom conditions like `@DisabledOnWindows` extremely simple.

**Comment by nicolaiparlog** [comment]
Thanks for the hint (links: [`EnabledIf`](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/context/junit/jupiter/EnabledIf.java), [`DisabledIf`](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/context/junit/jupiter/DisabledIf.java)), didn't know about that. I'd like to keep dependencies to a minimum but I'll think about it.

Regarding generalizations, I was exploring ideas to get the compiler to check conditions. But I'll start with the simple cases...

**Comment by sbrannen** [comment]
> Thanks for the hint (links: EnabledIf, DisabledIf), didn't know about that. 

You're welcome.

> I'd like to keep dependencies to a minimum but I'll think about it.

Sure. I wasn't implying that you should re-implement or copy them. Rather, I meant for them to serve as possible inspiration. Although supporting an expression language of any sort in core JUnit would naturally require the EL implementation to be an optional dependency. Anyway, just _food for thought_.

> Regarding generalizations, I was exploring ideas to get the compiler to check conditions.

Can you expound on that?

**Comment by nicolaiparlog** [comment]
Spawned #2 and added as a task to the issue description.

**Comment by nicolaiparlog** [comment]
Spawned #3 to continue discussion about generalized conditions there.

**Comment by sormuras** [comment]
A `DisabledOn("java.version", "^9.*")` would be convenient to have here: https://github.com/junit-team/junit5/pull/598/files -- with first parameter pointing to a `System` property key and the second parameter is a regex pattern to match.

**Comment by nicolaiparlog** [comment]
Good point about the Java version, I added an item to the checkbox list in the issue description.

**Comment by jbduncan** [comment]
My knowledge of annotations is pretty limited, so I've no idea if what I'm going to suggest is even feasible, but here goes!

How about a `@DisabledOn(BooleanSupplier)` annotation that disables if the supplier evaluates to `true`, but doesn't if it evaluates to `false`?

**Comment by nicolaiparlog** [comment]
@jbduncan: I considered something like that and was halfway done implementing it when I realized that annotations can only use constants as fields. Now I'm toying with the though to name a static field that us a `BooleanSupplier` and gets evaluated.

**Comment by nicolaiparlog** [comment]
@smoyer64 [wrote]:

> We should probably have a discussion about the disabling extensions as I have some that overlap. I started with @EnableIf and @DisableIf with a predicate as the value and another String as a message template. Then I built everything else on that. I have @EnableIfOs (and disable) in the middle and specific annotations at the end.
>
> This code is not done but I like the generic nature of the extension and how you add new annotations with only their associated classes. I'll get what I have checked into the old selesy project so you can assess it.

That is excellent! As you can see above (particularly [here](https://github.com/junit-pioneer/junit-pioneer/issues/1#issuecomment-261769658)) I started on the specific end but planned to go that very direction. I did some experiments and also tried to support predicates. I failed to find a way around the fact that you can not define a lambda as an annotation argument and found no other solution I immediately liked. I'm curious to see which way you went.

**Comment by nicolaiparlog** [comment]
Just had this idea: An enabled/disabled extension with which you can form Boolean formulas over existing extensions: `@DisabledIf(and(EnabledOnLinux.class, DisabledOnJava9.class))`.

**Comment by smoyer64** [comment]
You can't put the code for a lambda in an annotation but you can put the
name of a class that implements predicate ... your example is a bit harder
as a repeatable annotation would effectively be an or (but you're still
using classes to specify the predicates.

On Jul 2, 2017 10:04 AM, "Nicolai Parlog" <notifications@github.com> wrote:

Just had this idea: An enabled/disabled extension with which you can form
Boolean formulas over existing extensions:
@DisabledIf(and(EnabledOnLinux.class,
DisabledOnJava9.class)).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/junit-pioneer/junit-pioneer/issues/1#issuecomment-312493765>,
or mute the thread

**Comment by smoyer64** [comment]
@nicolaiparlog I've committed the POC code I had for ```@DisabledIf``` along with a predicate for OS and a meta-annotation (```@DisabledIfOperatingSystemIsLinux```).  This code isn't anywhere near done and it certainly needs some tests written if we decide to go this way but it does allow the user to write new predicates that determine enabling or disabling.  As I noted in the commit, ```@EnableIf``` is simply the logical negation of the ```@DisabledIfExtension```.

See https://github.com/selesy/junit5-extensions/blob/develop/junit5-extensions-disable-rest-extension/src/main/java/com/selesy/testing/junit5/extensions/disable/rest/os/DisabledIfOperatingSystemIsLinux.java

**Comment by ttddyy** [comment]
Hi @smoyer64

As @sbrannen mentioned, spring already uses `@DisabledIf` annotation.
From user's perspective, it would be nice that annotation names don't collide.
If same names are used, users need to check the import statement for which `@DisabledIf` is used or need to use full package name especially both `@DisabledIf` annotations are used in single file.

So, just IMO for junit-pioneer, naming `@DisabledIf` to `@DisabledWhen` or similar might be a tiny good thing for users.

**Comment by sbrannen** [comment]
I'm afraid that multiple projects in this world will come up with an annotation named `@DisabledIf`.

TBH, I tried to come up with a better name for Spring, but in the end I figured `@DisabledIf` was better than something like `@DisabledIfSpel`.

So I think the conflicts are unavoidable.

In any case, it's definitely something to keep in mind.

**Comment by sbrannen** [comment]
@nicolaiparlog, FYI: there's been a _very simplistic_ PoC for a system property condition [here](https://github.com/junit-team/junit5/blob/6e707fac4c590da8b759a29ca236e1e34c5abd8f/junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/sub/SystemPropertyCondition.java) for quite some time. That also serves as a PoC for an environment variable condition. Of course, I'd come up with a better name than `@SystemProperty` if I were to publish it.

**Comment by smoyer64** [comment]
@ttddyy - I think the name is apropos of its function and don't mind that it collides.  There's a large population of JUnit users that doesn't use Spring and some words are just right - even early versions of the JDK had java.util.Date and java.sql.Date.

I've also got a set of temporal conditions that are tentatively using ```@DisabledBefore```, ```@DisabledAfter``` and ```@DisabledBetween```.

Unfortunately, naming is hard - I do like the fact that the Spring version accepts EL and that was something I was considering after Java 9 (we should be able to ```exec``` code then).  I think the real question is whether we can create something that's worth importing into a Spring project!

**Comment by sbrannen** [comment]
>  I think the real question is whether we can create something that's worth importing into a Spring project!

Yep.... that will be the real challenge!

Because... with SpEL support in Spring's `@EnabledIf`, you can basically implement 90% of the conditions proposed in _this_ issue as one-liners, like [`@EnabledOnMac`](https://github.com/spring-projects/spring-framework/blob/e0de7754cc7138d242ed987d80986f424bff71f5/spring-test/src/test/java/org/springframework/test/context/junit/jupiter/EnabledOnMac.java), which basically just boils down to the following one-liner (if you don't want a custom annotation).

```java 
@EnabledIf(expression = "#{systemProperties['os.name'].toLowerCase().contains('mac')}", reason = "Enabled on Mac OS")
```

**Comment by mkobit** [comment]
I wonder if something similar to how `@ParameterizedTest` is structured would be useful here? Then different implementations of _enable if_ and _disable if_ could be implemented by consumers with not too much effort.

Incomplete code below, but would allow for the solution up above (I think) as well as other possible implementations (System property, environment variable, etc.):

```java
public class DisabledIfConditionalExecution implements ExecutionCondition {

  @Override
  ConditionEvaluationResult evaluateExecutionCondition(ExtensionContext context) {
    // ...
  }
}

public @interface DisabledIf {
}

public @interface DisabledIfSource {
  Class<? extends DisabledIfProvider> value();
}

public interface DisabledIfProvider {
  boolean isDisabled(ExtensionContext context);
}

@DisabledIfSource(DisabledIfSpelProvider.class)
@interface DisabledIfSpel {
  String expression();
  String reason();
}

class DisabledIfSpelProvider implements DisabledIfProvider {
  boolean isDisabled(ExtensionContext context) {
    // ...
  }
}

class MyTest {
  @DisabledIfSpel(expression = "#{systemProperties['os.name'].toLowerCase().contains('mac')}", reason = "Enabled on Mac OS")
  void myTest() {
  }
}
```

**Comment by mkobit** [comment]
Related to https://github.com/junit-team/junit5/issues/219 as well.

**Comment by sormuras** [comment]
For the record and some-what related to this initial pioneer issue: there's a new label for "pioneer" ideas at https://github.com/junit-team/junit5/issues?q=is%3Aissue+is%3Aopen+label%3A%223rd-party%3A+pioneer%22 -- tagging issues that may be interesting for @junit-pioneer

**Comment by nicolaiparlog** [comment]
@sormuras Can you take a look at my initial bullet point list and tell us which ideas Jupiter already ~~stole~~ implemented. :wink:

**Comment by sbrannen** [comment]
I'm not @sormuras, but I'll update this issue's description to check off what's already covered. 😉

**Comment by sbrannen** [comment]
done

**Comment by nicolaiparlog** [comment]
@sbrannen: Thank you for the input. :smiley_cat:

@all: From the three unchecked ones, I consider each fair game, particularly `@DisabledUntil`. If anyone wants to tackle these, feel free to do so.

**Comment by smoyer64** [comment]
@nicolaiparlog The conditional disabling of tests was something we were both working in before joining forces - there's a @DisableRest in the portion of selesy/junit-extension I had asked you to review a while ago (https://github.com/selesy/junit5-extensions/tree/develop/junit5-extensions-disable-rest-extension/src/main/java/com/selesy/testing/junit5/extensions/disable/rest).  Will this satisfy the "disable all but one" criteria?  It's a bit more than that because if you annotate (e.g.) two of ten tests they'll both run.

I should also note that I don't really like the name - Rest is not REST but Roy Fielding has effectively defined the meaning of that word for developers.  Perhaps @DisableOthers?

**Comment by marcphilipp** [comment]
In the Javascript frameworks I‘ve used that‘s usually called `only`.

**Comment by nicolaiparlog** [comment]
Opened #71 for `@DisableOthers`/`@DisableRest`/`@EnableOnly`/whatever.

**Comment by nicolaiparlog** [comment]
At least the last two items from the opening post still sound interesting to me. If anybody else shares that, PRs are welcome. :)

**Comment by Bukama** [comment]
By @nicolaiparlog in #163, because I think it might be helpful here too:

> We just updated to Jupiter 5.5 (#278) to use the new [`InvocationInterceptor`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/InvocationInterceptor.html) API. _If_ that API gets called for individual parameterized test invocations, it would be a very powerful way to implement disabling parameterized tests. The provided [`Invocation`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/InvocationInterceptor.Invocation.html) allows skipping tests and the [`ReflectiveInvocationContext`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ReflectiveInvocationContext.html) seems to give access to the actual arguments. Someone should look into that and possibly create an issue if the approach seems promising. 😊

**Comment by nipafx** [comment]
@mkobit I never replied to [your proposal above](https://github.com/junit-pioneer/junit-pioneer/issues/1#issuecomment-318861086). I liked the idea a lot and was about to create an issue for it when I was pointed at Jupiter's [custom conditions](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-custom), which provide all the features your proposal does. Main difference: Jupiter's solution is a bit simpler, but yours is type safe and survives refactorings. I don't think that's enough to warrant our own implementation, so I won't create that issue.

**Comment by nipafx** [comment]
As I see it, we've covered all ideas in this issue, so we can finally close it. 🥳
