### ISSUE TITLE
@CartesianProductTest extension

### ISSUE THREAD

**Issue by sormuras** [junit-pioneer/junit-pioneer#68]
## Overview

Provide a similar, but complete and fleshed-out, extension that provides a `@CartesianProductTest` annotation implemention.

### Usage outline

```java
@CartesianProductTest({"0", "1"})
void threeBits(String a, String b, String c) {
	int value = Integer.parseUnsignedInt(a + b + c, 2);
	assertTrue((0b000 <= value) && (value <= 0b111));
}

@CartesianProductTest
@DisplayName("S ⨯ T ⨯ U")
void nFold(String string, Class<?> type, TimeUnit unit, TestInfo info) {
	assertTrue(string.endsWith("a"));
	assertTrue(type.isInterface());
	assertTrue(unit.name().endsWith("S"));
	assertTrue(info.getTags().isEmpty());
}

static CartesianProductTest.Sets nFold() {
	return new CartesianProductTest.Sets()
			.add("Alpha", "Omega")
			.add(Runnable.class, Comparable.class, TestInfo.class)
			.add(TimeUnit.DAYS, TimeUnit.HOURS);
}
```

### Implementation idea

https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-extensions/src/main/java/com/example/cartesian

### Todos

- [ ] Copy sources from `junit5-jupiter-extensions` and adopt to pioneers' (package) structure.
- [ ] Write unit and integration tests for the `@CartesianProductTest` and its provider.
- [ ] Support more basic types in the annotation, in addition to `String`?
- [ ] Document usage and limitations

**Comment by sormuras** [comment]
Ideally the `@CartesianProductTest` would be able to reuse any existing argument source, including the `@RangeSource` described in #123. For example:

```java
@CartesianProductTest
@EnumSource(TimeUnit.class)
@ValueSource(ints = {1, 2, 3})
@RangeSource(2, 10, 2)
void test(TimeUnit unit, int a, int b) {...}
```

**Comment by marcphilipp** [comment]
The method would be called with {0, 1} × {0, 1} × {0, 1} = [(0,0,0), (0,0,1), ..., (1,1,1)].

**Comment by matthieu-vergne** [comment]
I see. It seems to me quite specific and unnatural, though. I would prefer to write it with something more explicit, like:
```java
enum BinaryString {"0", "1"}

@CartesianProductTest
@EnumSource(BinaryString.class)
@EnumSource(BinaryString.class)
@EnumSource(BinaryString.class)
void threeBits(String a, String b, String c) {
	int value = Integer.parseUnsignedInt(a + b + c, 2);
	assertTrue((0b000 <= value) && (value <= 0b111));
}
```

It seems a lot clearer to me that way.
Just a piece of opinion.

**Comment by marcphilipp** [comment]
@sormuras @sbrannen Does Java guarantee that annotations are returned by reflection in the order they are defined in the source code?

**Comment by sbrannen** [comment]
Yes. According to the JLS, the order is “left to right” , which most humans understand better as “top to bottom”. Otherwise, the order of repeatable annotations _outside_ their container could not be guaranteed.

**Comment by aepfli** [comment]
is this still up for grabs? looks interesting and if okay, i will give it a shot!

**Comment by nicolaiparlog** [comment]
Yeah, it is, give it a shot. :+1:

Not sure about the others, but I really like the idea to make it interact with other argument sources. Maybe it could even _require_ that values for all arguments are provided by dedicated sources and `CartesianProductTestExtension` "just" orchestrates them?

Whatever you do, though, I recommend to start small and ask for feedback early. In my mind, the feature is still very vague, and we don't want you spending a lot of time on refining docs and tests before we're sure what it looks like.

**Comment by nicolaiparlog** [comment]
Let me know when you start on it and I'll assign the issue to you.

**Comment by matthieu-vergne** [comment]
\\{^o^}/ Thanks!
Hope to try it soon!

I am not familiar with the releasing strategy of JUnit Pionner and how it integrates into JUnit.
Could you tell me when it will be released and pinpoint me to resources explaining how to use it in my project?

**Comment by gtsh** [comment]
I'm wondering, why we put up with the additional @CartesianProductTest and the ambiguity of having multiple @..Source annotations, instead of reusing @ParameterizedTest, and and allow to add the @..Source annotiations to be added to the tests paramters  (using @Target({ ElementType.ANNOTATION_TYPE, ElementType.METHOD, ElementType.PARAMETER }) like so:

@ParameterizedTest
void test(@ValueSource(ints = {1, 2}) int i, @ValueSource(ints = {3, 4}) int j) {

}

This would make up for a far more consistent coding experience...

**Comment by Michael1993** [comment]
We do not have access to JUnit source code - `@ValueSource` is not ours, it's theirs. So, we can not modify `@ValueSource`. It has `@Target({ ElementType.ANNOTATION_TYPE, ElementType.METHOD })`, which means it can not be used on a parameter.
We can not modify `@ParameterizedTest` for the same reasons.

There are also differences in the approach of the extensions (ParameterizedTest is an extension too). CartesianProductTests want to test the combination of inputs from multiple sources. ParameterizedTests want to test the inputs from a single source.

We _could_ target parameters. Something like this:
```java
@CartesianProductTest
void test(
    @CartesianValueSource(ints = {1, 2, 3}) int i
    @CartesianValueSource(strings = {"A", "B"}) String s) {
    // some test code here
}
```

If you think that's a good improvement, please open a new issue. If you feel the documentation of CartesianProductTest should include an explanation about the differences from ParameterizedTest, please open a new issue (these do not have to be separate issues).

**Comment by matthieu-vergne** [comment]
I like the idea of tagging the parameters.
If an issue is open on that topic, please share its link here.
